name: Build and Push Docker Images

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: {}

env:
  DOCKERHUB_REPO: googlesky/kali-desktop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        desktop: [ xfce, lxde, kde ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: googlesky
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build temporary image to read Kali VERSION
        run: |
          docker build \
            --build-arg KALI_DESKTOP=${{ matrix.desktop }} \
            -t temp-kali-desktop:${{ matrix.desktop }} \
            -f Dockerfile .
          VERSION=$(docker run --rm --entrypoint '' temp-kali-desktop:${{ matrix.desktop }} bash -lc '. /etc/os-release && echo -n "$VERSION"')
          echo "KALI_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        run: |
          TAGS="-t $DOCKERHUB_REPO:${{ matrix.desktop }}"
          if [ -n "${KALI_VERSION:-}" ]; then
            TAGS="$TAGS -t $DOCKERHUB_REPO:${KALI_VERSION}-${{ matrix.desktop }}"
          fi
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg KALI_DESKTOP=${{ matrix.desktop }} \
            -f Dockerfile \
            $TAGS \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .


